name: Deploy CTRL Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install deps
        working-directory: web
        run: npm ci

      - name: Build
        working-directory: web
        run: npm run build

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
        env:
          HOST: ${{ secrets.HOST }}

      - name: Write SSH key
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Upload build to staging (deploy-tmp)
        run: |
          rsync -avz --delete web/dist/ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/deploy-tmp/
      
      - name: Promote release on server
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} "~/bin/deploy_frontend.sh"
